from __future__ import annotations

import os
from typing import Any

import httpx

from app.core.settings import settings


class ExplanationResult(dict):
    summary: str
    provider: str
    model: str


class DecisionExplanationAgent:
    """Faithful explanation layer for human feedback records."""

    def explain(self, record: dict[str, Any]) -> str:
        result = self.explain_with_metadata(record)
        return str(result["summary"])

    def explain_with_metadata(self, record: dict[str, Any]) -> ExplanationResult:
        provider = (settings.explainer_provider or "rule").strip().lower()
        if provider == "groq":
            print("Explaining using LLM")
            print(record)
            groq_result = self._explain_with_groq(record)
            if groq_result is not None:
                return groq_result
        return self._explain_with_rule(record)

    def explain_refinement_with_metadata(
        self,
        record: dict[str, Any],
        accepted_ids: list[int],
        preference_profile: dict[str, Any],
        round_index: int,
    ) -> ExplanationResult:
        provider = (settings.explainer_provider or "rule").strip().lower()
        if provider != "groq":
            raise RuntimeError(
                "Refinement summary requires explainer_provider=groq so the text is AI-generated."
            )

        llm_result = self._explain_refinement_with_groq(record, accepted_ids, preference_profile, round_index)
        if llm_result is None:
            raise RuntimeError(
                "Refinement summary could not be generated by AI. Check GROQ_API_KEY and model settings."
            )
        return llm_result

    def _explain_with_rule(self, record: dict[str, Any]) -> ExplanationResult:
        decisions = record.get("decisions", [])
        accepted = [d for d in decisions if d["decision"] == "accepted"]
        rejected = [d for d in decisions if d["decision"] == "rejected"]

        accepted_ids = ", ".join(str(d["variation_id"]) for d in accepted) or "none"
        rejected_ids = ", ".join(str(d["variation_id"]) for d in rejected) or "none"

        reasons = [
            f"Variation {d['variation_id']}: {d.get('reason', '').strip()}"
            for d in decisions
            if d.get("reason", "").strip()
        ]
        reason_text = " User notes: " + " | ".join(reasons) if reasons else ""

        summary = (
            f"The user kept studio look(s): {accepted_ids}. "
            f"The user passed on studio look(s): {rejected_ids}. "
            "The final selection reflects the recorded feedback and should be used as the "
            "decision trace for this editing session."
            f"{reason_text}"
        )
        return ExplanationResult(summary=summary, provider="rule", model="rules-v1")

    def _explain_with_groq(self, record: dict[str, Any]) -> ExplanationResult | None:
        api_key = (settings.groq_api_key or os.getenv("GROQ_API_KEY", "")).strip()
        if not api_key:
            return None

        context = self._build_history_context(record)
        system_prompt = (
            "You are a faithful explanation engine for an AI portrait workflow. "
            "Use only the provided JSON facts. Do not invent data. "
            "If human commentary exists (free-text reasons from the user), prioritize it above all "
            "other signals and treat it as the primary evidence for the explanation. "
            "Write one concise paragraph that explains: what the user kept/rejected, "
            "what generation parameters and traits likely drove outcomes, and how user feedback "
            "influenced refinement decisions across rounds."
        )
        user_prompt = (
            "Summarize this session history and explain why results were generated as they were. "
            "Reference concrete fields from the JSON context. "
            "When human commentary is present, anchor most of the explanation in that commentary "
            "and only use model/settings metadata as supporting context.\n\n"
            f"SESSION_CONTEXT_JSON:\n{context}"
        )

        payload = {
            "model": settings.groq_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.2,
            "max_completion_tokens": 380,
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        try:
            endpoint = f"{settings.groq_base_url.rstrip('/')}/chat/completions"
            timeout = max(10, int(settings.groq_timeout_seconds))
            with httpx.Client(timeout=timeout) as client:
                response = client.post(endpoint, headers=headers, json=payload)
            if response.status_code >= 400:
                return None
            body = response.json()
            choices = body.get("choices") or []
            if not choices:
                return None
            content = (choices[0].get("message") or {}).get("content")
            summary = str(content or "").strip()
            if not summary:
                return None
            return ExplanationResult(summary=summary, provider="groq", model=settings.groq_model)
        except Exception:
            return None

    def _explain_refinement_with_groq(
        self,
        record: dict[str, Any],
        accepted_ids: list[int],
        preference_profile: dict[str, Any],
        round_index: int,
    ) -> ExplanationResult | None:
        api_key = (settings.groq_api_key or os.getenv("GROQ_API_KEY", "")).strip()
        if not api_key:
            return None

        context = {
            "session_id": record.get("session_id"),
            "mode": record.get("mode"),
            "base_seed": record.get("base_seed"),
            "refinement_round": round_index,
            "accepted_ids": accepted_ids,
            "selection_notes": [
                {
                    "variation_id": item.get("variation_id"),
                    "decision": item.get("decision"),
                    "reason": str(item.get("reason", "")).strip(),
                }
                for item in (record.get("decisions") or [])
                if str(item.get("reason", "")).strip()
            ],
            "current_variations": [
                {
                    "id": v.get("id"),
                    "label": v.get("label"),
                    "prompt": v.get("prompt"),
                    "strength": v.get("strength"),
                    "guidance_scale": v.get("guidance_scale"),
                }
                for v in (record.get("variations") or [])
            ],
            "preference_profile": preference_profile,
            "decision_history": record.get("decision_history", []),
        }

        system_prompt = (
            "You are an AI refinement director for a portrait generation workflow. "
            "Use only the JSON context. Do not invent facts. "
            "Selection notes (free-text reasons) are the highest-priority signal. "
            "When notes exist, anchor most of your explanation in those notes and never contradict them. "
            "Treat model settings as secondary support only. "
            "Write one concise paragraph for the user that: "
            "(1) references approved looks, "
            "(2) explains likely preference direction, and "
            "(3) gives concrete review focus for the next keep/pass round."
        )
        user_prompt = (
            "Generate the refinement note for the next iteration. "
            "Anchor to the provided accepted IDs, variation labels, prompts, and preference profile. "
            "Strongly prioritize selection_notes text over inferred traits or parameter metadata. "
            "If notes and metadata conflict, follow notes. "
            "Avoid boilerplate and avoid claiming anything not present in JSON.\n\n"
            f"REFINEMENT_CONTEXT_JSON:\n{context}"
        )

        payload = {
            "model": settings.groq_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.25,
            "max_completion_tokens": 220,
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        try:
            endpoint = f"{settings.groq_base_url.rstrip('/')}/chat/completions"
            timeout = max(10, int(settings.groq_timeout_seconds))
            with httpx.Client(timeout=timeout) as client:
                response = client.post(endpoint, headers=headers, json=payload)
            if response.status_code >= 400:
                return None
            body = response.json()
            choices = body.get("choices") or []
            if not choices:
                return None
            content = (choices[0].get("message") or {}).get("content")
            summary = str(content or "").strip()
            if not summary:
                return None
            return ExplanationResult(summary=summary, provider="groq", model=settings.groq_model)
        except Exception:
            return None

    def _build_history_context(self, record: dict[str, Any]) -> dict[str, Any]:
        generation_history = record.get("generation_history") or []
        decision_history = record.get("decision_history") or []
        refinement_history = record.get("refinement_history") or []

        current_commentary = [
            {
                "variation_id": item.get("variation_id"),
                "decision": item.get("decision"),
                "reason": str(item.get("reason", "")).strip(),
            }
            for item in (record.get("decisions") or [])
            if str(item.get("reason", "")).strip()
        ]

        historical_commentary = []
        for entry in decision_history:
            for item in (entry.get("decisions") or []):
                reason = str(item.get("reason", "")).strip()
                if not reason:
                    continue
                historical_commentary.append(
                    {
                        "round": entry.get("round"),
                        "decided_at": entry.get("decided_at"),
                        "variation_id": item.get("variation_id"),
                        "decision": item.get("decision"),
                        "reason": reason,
                    }
                )

        compact_generations = []
        for item in generation_history:
            compact_generations.append(
                {
                    "round": item.get("round"),
                    "mode": item.get("mode"),
                    "base_seed": item.get("base_seed"),
                    "preserve_faces": item.get("preserve_faces"),
                    "variations": [
                        {
                            "id": v.get("id"),
                            "label": v.get("label"),
                            "provider": v.get("provider"),
                            "strength": v.get("strength"),
                            "guidance_scale": v.get("guidance_scale"),
                        }
                        for v in (item.get("variations") or [])
                    ],
                }
            )

        return {
            "session_id": record.get("session_id"),
            "mode": record.get("mode"),
            "base_seed": record.get("base_seed"),
            "refinement_round": record.get("refinement_round", 0),
            "human_commentary_present": bool(current_commentary or historical_commentary),
            "current_human_commentary": current_commentary,
            "historical_human_commentary": historical_commentary,
            "current_variations": [
                {
                    "id": v.get("id"),
                    "label": v.get("label"),
                    "provider": v.get("provider"),
                    "strength": v.get("strength"),
                    "guidance_scale": v.get("guidance_scale"),
                }
                for v in (record.get("variations") or [])
            ],
            "current_decisions": record.get("decisions", []),
            "preference_profile": record.get("preference_profile", {}),
            "generation_history": compact_generations,
            "decision_history": decision_history,
            "refinement_history": refinement_history,
        }


def accepted_rejected_ids(decisions: list[dict[str, Any]]) -> tuple[list[int], list[int]]:
    accepted = [item["variation_id"] for item in decisions if item["decision"] == "accepted"]
    rejected = [item["variation_id"] for item in decisions if item["decision"] == "rejected"]
    return accepted, rejected
